version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /fixtures/lerna-scopes
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /fixtures/lerna-scopes/packages/first-package
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /fixtures/lerna-scopes/packages/second-package
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
